version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'monthly'
      assignees:
          - 'hougesen'
      open-pull-requests-limit: 25

    - package-ecosystem: 'npm'
      directory: '/www'
      schedule:
          interval: 'monthly'
      assignees:
          - 'hougesen'
      open-pull-requests-limit: 25

    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'monthly'
      assignees:
          - 'hougesen'
      open-pull-requests-limit: 25
